name: Build and Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t gymtracker .

      - name: Save Docker image
        run: docker save gymtracker | gzip > gymtracker.tar.gz

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Copy image to EC2
        run: scp -i private_key.pem -o StrictHostKeyChecking=no gymtracker.tar.gz ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ec2-user/

      - name: Deploy on EC2
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker load -i /home/ec2-user/gymtracker.tar.gz
            docker stop gymtracker || true
            docker rm gymtracker || true
            docker run -d -p 8080:8080 --name gymtracker gymtracker
          EOF
