name: Build and Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t gymtracker .

      - name: Save Docker image to tar
        run: docker save gymtracker:latest | gzip > gymtracker.tar.gz

      - name: Copy image to EC2
        run: scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa gymtracker.tar.gz ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/

      - name: Load and run container on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            docker load < /home/ec2-user/gymtracker.tar.gz
            docker stop gymtracker || true
            docker rm gymtracker || true
            docker run -d -p 8080:8080 --name gymtracker gymtracker:latest
          EOF
