name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/aws-gym-tracker
            git pull origin main
            docker build -t gymtracker .
            # Stop and remove any container using port 8080
            docker ps -q --filter "publish=8080" | xargs -r docker stop
            docker ps -aq --filter "publish=8080" | xargs -r docker rm
            # Stop/remove gymtracker container if it exists
            docker stop gymtracker || true
            docker rm gymtracker || true
            # Run new container
            docker run -d -p 8080:8080 --name gymtracker gymtracker
          EOF
